# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/14832/Documents/study/CS/moshu/labs/lab10/balance/balance.cache/wt [current_project]
set_property parent.project_path C:/Users/14832/Documents/study/CS/moshu/labs/lab10/balance/balance.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/Users/14832/Documents/study/CS/moshu/labs/lab10/balance/ip_repo/ADXL362Control_1.0 [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/14832/Documents/study/CS/moshu/labs/lab10/balance/balance.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {
  C:/Users/14832/Documents/study/CS/moshu/labs/lab10/balance/materials/balance2.mem
  C:/Users/14832/Documents/study/CS/moshu/labs/lab10/balance/materials/balance2_palette.mem
  C:/Users/14832/Documents/study/CS/moshu/labs/lab10/balance/materials/balance2_alpha.mem
}
read_verilog -library xil_defaultlib {
  C:/Users/14832/Documents/study/CS/moshu/labs/lab10/balance/ballMove.v
  C:/Users/14832/Documents/study/CS/moshu/labs/lab10/balance/calculateV.v
  C:/Users/14832/Documents/study/CS/moshu/labs/lab10/balance/calculateX.v
  C:/Users/14832/Documents/study/CS/moshu/labs/lab10/balance/classicPos.v
  C:/Users/14832/Documents/study/CS/moshu/labs/lab10/balance/drawScreen.v
  C:/Users/14832/Documents/study/CS/moshu/labs/lab10/balance/drawSingleLayer.v
  C:/Users/14832/Documents/study/CS/moshu/labs/lab10/balance/dropInHoles.v
  C:/Users/14832/Documents/study/CS/moshu/labs/lab10/balance/getRandPos.v
  C:/Users/14832/Documents/study/CS/moshu/labs/lab10/balance/layerControl.v
  C:/Users/14832/Documents/study/CS/moshu/labs/lab10/balance/myAccelerometerCtrl.v
  C:/Users/14832/Documents/study/CS/moshu/labs/lab10/balance/positionConflict.v
  C:/Users/14832/Documents/study/CS/moshu/labs/lab10/balance/random.v
  C:/Users/14832/Documents/study/CS/moshu/labs/lab10/balance/sig_clr.v
  C:/Users/14832/Documents/study/CS/moshu/labs/lab10/balance/sig_pulse.v
  C:/Users/14832/Documents/study/CS/moshu/labs/lab10/balance/sram.v
  C:/Users/14832/Documents/study/CS/moshu/labs/lab10/balance/vga320x180.v
  C:/Users/14832/Documents/study/CS/moshu/labs/lab10/balance/main.v
}
read_ip -quiet C:/Users/14832/Documents/study/CS/moshu/labs/lab10/balance/balance.srcs/sources_1/ip/ADXL362Control_0/ADXL362Control_0.xci

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/14832/Documents/study/CS/moshu/labs/lab10/balance/Nexys-4-DDR-Master.xdc
set_property used_in_implementation false [get_files C:/Users/14832/Documents/study/CS/moshu/labs/lab10/balance/Nexys-4-DDR-Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
